/* !!!!!!! This file is autogenerated. DO NOT MODIFY !!!!!!! */
require('angular');



export default {
  'demo': angular.module('demo', [])
    .directive('center',                      require('./directives/center'))
    .directive('helloWorld',                  require('./directives/helloWorld'))
    .directive('selfie',                      require('./directives/selfie'))
    .directive('spinner',                     require('./directives/spinner'))


};
/* !!!!!!! This file is autogenerated. DO NOT MODIFY !!!!!!! */