/* !!!!!!! This file is autogenerated. DO NOT MODIFY !!!!!!! */
require('angular');

require('angular-route');

export default {
  'demo': angular.module('demo', ['ngRoute'])
    .directive('welcome',                     require('./directives/welcome'))
    .directive('center',                      require('./directives/center'))
    .directive('helloWorld',                  require('./directives/helloWorld'))
    .directive('selfie',                      require('./directives/selfie'))
    .directive('spinner',                     require('./directives/spinner'))

    .config(require('./routes').default)
    .config(require('./config').default)
};
/* !!!!!!! This file is autogenerated. DO NOT MODIFY !!!!!!! */