/* !!!!!!! This file is autogenerated. DO NOT MODIFY !!!!!!! */

import demo from './modules/demo';

export default {
  'demo': demo['demo']
};

/* !!!!!!! This file is autogenerated. DO NOT MODIFY !!!!!!! */